[package]
name = "function_from_equation"
description = "Creates a function from a math equation"
version = "0.1.0"
edition = "2021"
license = "LICENSE"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true

[dependencies]
